services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Expose Vite's default port
    volumes:
      - .:/app # Bind mount for live updates during development
      - /app/node_modules # Prevents overwriting node_modules in the container
    environment:
      - NODE_ENV=development

    command: ["npm", "run", "dev"]
